In [ ]:
import numpy as np
#1. Create a numpy array of size 2 x 2
a = np.array([[1,2],[3,4]])
print(a.shape)
print(a)

(2, 2)
[[1 2]
 [3 4]]


In [ ]:
#2. Create a random numpy array of size 3 x 4
b = np.random.random((3,4))
print(b.shape)
print(b)

(3, 4)
[[0.51936599 0.80483391 0.27852416 0.99361968]
 [0.35787216 0.54392257 0.74070316 0.29992374]
 [0.493319   0.10326289 0.3800042  0.58843481]]


In [ ]:
#3. Create a numpy array of ones and a numpy array of zeroes
c = np.ones((2,2))
d = np.zeros((2,2))
print(c)
print(d)

[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]


In [ ]:
#4. Create a random numpy array of size 6x3 and transpose it
e = np.random.random((6,3))
print(e)
print("\nAfter transpose: ")
print(e.T)

[[0.14248503 0.43598506 0.58487984]
 [0.02593196 0.2325217  0.15143946]
 [0.79320288 0.98429512 0.9396319 ]
 [0.83704723 0.33352926 0.46142715]
 [0.50916577 0.8532679  0.51848324]
 [0.30842525 0.50965213 0.71429115]]

After transpose: 
[[0.14248503 0.02593196 0.79320288 0.83704723 0.50916577 0.30842525]
 [0.43598506 0.2325217  0.98429512 0.33352926 0.8532679  0.50965213]
 [0.58487984 0.15143946 0.9396319  0.46142715 0.51848324 0.71429115]]


In [ ]:
#5. Create two random numpy array of size n x p and p x m and then compute the dot product
f = np.random.random((2,3))
g = np.random.random((3,4))
print(f)
print(g)
print("\nAfter dot product: ")
print(np.dot(f,g))

[[0.39968337 0.0100789  0.34079423]
 [0.20119962 0.88619457 0.09869208]]
[[0.1148875  0.9800369  0.76502342 0.96431523]
 [0.00208909 0.19770386 0.19439538 0.4580982 ]
 [0.91748362 0.17923136 0.94204355 0.99934946]]

After dot product: 
[[0.3586128  0.4547781  0.62876943 0.73061041]
 [0.11551503 0.39007585 0.41916679 0.69861187]]
